config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#dashboard'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  # get '/dashboard', to: 'sessions#dashboard'

  devise_scope :user do
    root 'sessions#dashboard', as: :authenticated_root
    resources :workers
    # resources :projects
    resources :clients do
      get 'bills', to: 'clients#bills'
    end
    resources :bills
    resources :projects do
      get 'bills', to: 'projects#bills'
    end
  end

  root 'devise/sessions#new'
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  has_many :bills
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :address, presence: true
  validates :phone, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  def paid_bills
    bills.paid_bills
  end

  def pending_bills
    bills.pending_bills
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :find_client, only: %i[show edit update destroy bills]

  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: 'The client was created!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @client.update_attributes(client_params)
    redirect_to clients_path, notice: 'Updated successfully'
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: 'Deleted successfully'
  end

  def bills
    @bills = @client.bills
    @pending_bills = @client.pending_bills
    @paid_bills = @client.paid_bills
  end

  private

  def client_params
    params.require(:client).permit(:name, :address, :phone)
  end

  def find_client
    client_id = params[:id] || params[:client_id]
    @client = Client.find_by_id(client_id)
  end
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/views/clients/_form_fields.html.erb
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <div class="invalid-feedback">name</div>
</div>

<div class='form-group'>
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
  <div class="invalid-feedback">phone</div>
</div>

<div class='form-group'>
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  <div class="invalid-feedback">address</div>
</div>

app/views/clients/bills.html.erb
<h2><%= @client.name %> Bill Summary</h2>
<p>Summerise your bills here .</p>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#all-bills">All Bills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#pending-bills">Pending Bills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#paid-bills">Paid Bills</a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane container active" id="all-bills">
    <%= render 'bills/bills_info', bills: @bills, layout: '' %>
  </div>

  <div class="tab-pane container fade" id="pending-bills">
    <%= render 'bills/bills_info', bills: @pending_bills, layout: '' %>
  </div>

  <div class="tab-pane container fade" id="paid-bills">
    <%= render 'bills/bills_info', bills: @paid_bills,  layout: '' %>
  </div>
</div>

app/views/clients/edit.html.erb
<% provide(:title, "Create Client") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new client</h3>
      </div>
      <div class="card-body">
          <% if @client.errors.any? %>
            <div class= "alert alert-danger">
              <%= @client.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for @client do |f| %>
            
            <%= render "form_fields", f: f %>

            <%= f.submit "Update", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", clients_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>

app/views/clients/index.html.erb
<div class="jumbotron bg-light jumbotron-fluid text-center">
  <h3>Clients</h3>
</div>
<div class="Rtable Rtable--4cols Rtable--collapse js-RtableAccordions">
  <% @clients.each_with_index do |client, i| %>
    <%= link_to 'Edit', edit_client_path(client), class: 'btn btn-outline-success btn-sm' %>
    <%= link_to 'Delete', client_path(client), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: 'btn btn-outline-danger btn-sm' %>
    <%= link_to 'View Bills', client_bills_path(client), class: 'btn btn-outline-success btn-sm' %>
    <button class="Accordion" role="tab" aria-selected="false"><%= client.name %></button>
    <div class="Rtable-cell  Rtable-cell--head"><h3><%= client.try(:phone) %></h3></div>
    <p class="Rtable-cell"><%= client.try(:address) %></p>
  <% end %>
</div>

app/views/clients/new.html.erb
<% provide(:title, "Create Client") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new client</h3>
      </div>
      <div class="card-body">
          <% if @client.errors.any? %>
            <div class= "alert alert-danger">
              <%= @client.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for(:client, url: clients_path) do |f| %>
            
            <%= render "form_fields", f: f %>

            <%= f.submit "Save", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", root_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>