config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#dashboard'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  # get '/dashboard', to: 'sessions#dashboard'

  devise_scope :user do
    root 'sessions#dashboard', as: :authenticated_root
    resources :workers
    # resources :projects
    resources :clients do
      get 'bills', to: 'clients#bills'
    end
    resources :bills
    resources :projects do
      get 'bills', to: 'projects#bills'
    end
  end

  root 'devise/sessions#new'
end

app/models/bill.rb
# frozen_string_literal: true

class Bill < ApplicationRecord
  belongs_to :project
  belongs_to :client

  has_many :worker_entries, inverse_of: :bill, dependent: :destroy
  # has_many :workers, through: :worker_entries
  has_many :workers, -> { distinct }, through: :worker_entries

  accepts_nested_attributes_for :worker_entries

  validates :title, presence: true, length: { maximum: 50 }
  validates :labour_charge, presence: true
  validates :material_charge, presence: true
  validates :total_payable, presence: true
  validates :paid_amount, presence: true
  validates :balance_amount, presence: true
  validates :issued_at, presence: true

  validate :total_payable_is_greater
  validate :total_payable_is_correct

  scope :paid_bills, -> { select { |b| b.total_payable.to_f == b.paid_amount.to_f } }
  scope :pending_bills, -> { select { |b| b.total_payable.to_f != b.paid_amount.to_f } }

  def total_payable_is_greater
    errors.add(:paid_amount, 'No need to pay more than amount payable') if total_payable.to_f < paid_amount.to_f
  end

  def total_payable_is_correct
    sum_value = labour_charge.to_f + material_charge.to_f
    errors.add(:total_payable, 'Should be sum of material and labour charge') unless sum_value == total_payable.to_f
  end

  def number
    'PCB' + project_id.to_s + client_id.to_s + id.to_s
  end
end

app/controllers/bills_controller.rb
# frozen_string_literal: true

class BillsController < ApplicationController
  before_action :find_bill, only: %i[show edit update destroy]

  def index
    @bills = Bill.all
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)

    workers = params[:workers]
    worked_hours = params[:worked_hours]

    workers.each_with_index do |worker_id, index|
      @bill.worker_entries.build(worker_id: worker_id, worked_hours: worked_hours[index])
    end

    if @bill.save
      redirect_to bills_path, notice: 'The bill was created!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @bill.update_attributes(bill_params)
    redirect_to bills_path, notice: 'Updated successfully'
  end

  def destroy
    @bill.destroy
    redirect_to bills_path, notice: 'Deleted successfully'
  end

  private

  def bill_params
    params.require(:bill).permit(:project_id, :client_id, :title, :labour_charge, :material_charge, :total_payable,
                                 :paid_amount, :balance_amount, :issued_at, worker_entries_attributes: %i[id worker_id worked_hours _destroy])
  end

  def find_bill
    @bill = Bill.find_by_id(params[:id])
  end
end

app/helpers/bills_helper.rb
# frozen_string_literal: true

module BillsHelper
  def bill_sum_by(bills, key)
    bills.map(&key.to_sym).map(&:to_f).sum
  end
end

app/views/bills/_bills_info.html.erb
<% if bills.any? %>
  <% if layout == 'table' %>
    <table class="table table-hover table-responsive">
      <thead>
        <tr>
          <th>Bill No</th>
          <th>Title</th>
          <th>Date</th>
          <th>Total Payable</th>
          <th>Paid Amount</th>
          <th>Balance Amount</th>
        </tr>
      </thead>
      
      <tbody>
        <% bills.each_with_index do  |bill| %>
          <tr>
            <td><%= bill.number %></td>
            <td><%= bill.title %></td>
            <td><%= format_date(bill.issued_at) %></td>
            <td><%= bill.total_payable %></td>
            <td><%= bill.paid_amount %></td>
            <td><%= bill.balance_amount %></td>
          </tr>   
        <% end %>   
      </tbody>

      <tfooter>
        <tr>
          <th>Sum</th>
          <th></th>
          <th></th>
          <th><%= bill_sum_by(bills, 'total_payable') %></th>
          <th><%= bill_sum_by(bills, 'paid_amount') %></th>
          <th><%= bill_sum_by(bills, 'balance_amount') %></th>
        </tr>
      </tfooter>
    </table>
  <% else %>
    <div class="jumbotron bg-light jumbotron-fluid text-center">
      <h3>Total Bill Amount   : <%= bill_sum_by(bills, 'total_payable') %></h3>
      <h3>Total Paid Amount   : <%= bill_sum_by(bills, 'paid_amount') %></h3>
      <h3>Total Balance Amount: <%= bill_sum_by(bills, 'balance_amount') %></h3>
    </div>
    <div class="Rtable Rtable--4cols Rtable--collapse js-RtableAccordions">
      <% bills.each_with_index do |bill, i| %>
        <button class="Accordion" role="tab" aria-selected="false">
          <%= bill.number + " - Total: " + bill.total_payable + ' - Paid: ' +  bill.paid_amount + " - Balance: " +  bill.balance_amount %>
        </button>
        <div class="Rtable-cell  Rtable-cell--head"><h3> <%= bill.title %></h3></div>
        <div class="Rtable-cell  Rtable-cell--head"><h3>Project Name : <%= bill.project.name %></h3></div>
        <div class="Rtable-cell"><h3>Client Name : <%= bill.client.name %></h3></div>
        <div class="Rtable-cell"><h3>Labour Charge : <%= bill.labour_charge %></h3></div>
        <div class="Rtable-cell"><h3>Material Charge : <%= bill.material_charge %></h3></div>
        <div class="Rtable-cell"><h3>Total Payable : <%= bill.total_payable %></h3></div>
        <div class="Rtable-cell"><h3>Paid Amount: <%= bill.paid_amount %></h3></div>
        <div class="Rtable-cell"><h3>Balance Amount: <%= bill.balance_amount %></h3></div>
        <div class="Rtable-cell"><h3>Issued On: <%= bill.issued_at %></h3></div>

        <div class="Rtable-cell">
          <% if bill.worker_entries.any? %>
            <span class="badge badge-pill badge-success">Workers</span>
            <% bill.worker_entries.each_with_index do |entry, i| %>
              <h3> <%= entry.worker.name %> - <%= entry.worked_hours || 0 %> hrs</h3>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="jumbotron bg-light jumbotron-fluid text-center">
    <h3>There is no bills in this category</h3>
  </div>
<% end %>

app/views/bills/_form_fields.html.erb
<div class='form-group'>
  <%= f.label :project_id %>
  <%= f.collection_select(:project_id, Project.all, :id, :name, {}, { class: 'form-control'} ) %>
  <div class="invalid-feedback">project_id</div>
</div>


<div class='form-group'>
  <%= f.label :client_id %>
  <%= f.collection_select(:client_id, Client.all, :id, :name, {}, { class: 'form-control'}) %>
  <div class="invalid-feedback">client_id</div>
</div>

<div class='form-group'>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <div class="invalid-feedback">name</div>
</div>

<div class='row'>  
  <div class='form-group col-md-4'>
    <%= f.label :labour_charge %>
    <%= f.text_field :labour_charge, class: 'form-control', id: 'labour-charge', type: 'number' %>
    <div class="invalid-feedback">labour_charge</div>
  </div>

  <div class='form-group col-md-4'>
    <%= f.label :material_charge %>
    <%= f.text_field :material_charge, class: 'form-control', id: 'material-charge', type: 'number' %>
    <div class="invalid-feedback">material_charge</div>
  </div>

   <div class='form-group col-md-4'>
    <%= f.label :total_payable %>
    <%= f.text_field :total_payable, class: 'form-control', id: 'total-payable', readonly: true %>
    <div class="invalid-feedback">total_payable</div>
  </div>
</div>

<div class=row> 
  <div class='form-group col-md-6'>
    <%= f.label :paid_amount %>
    <%= f.text_field :paid_amount, class: 'form-control', id: 'paid-amount', type: 'number'  %>
    <div class="invalid-feedback">paid_amount</div>
  </div>

  <div class='form-group col-md-6'>
    <%= f.label :balance_amount %>
    <%= f.text_field :balance_amount, class: 'form-control', id: 'balance-amount', readonly: true  %>
    <div class="invalid-feedback">balance_amount</div>
  </div>
</div>

<div class='form-group'>
  <%= f.label :issued_at %>
  <%= f.date_field :issued_at, class: 'form-control' %>
  <div class="invalid-feedback">issued_at</div>
</div>

<% if action_name == 'edit' %>
  <%= f.fields_for :worker_entries do |worker_entry, i| %>
    <div class='row bg-light'>
      <div class='form-group col-md-6'>
        <%= worker_entry.collection_select(:worker_id, Worker.all, :id, :name, {},{ class: 'form-control'}) %>
        <div class="invalid-feedback">worker</div>
      </div>

      <div class='form-group col-md-6'>
        <%= worker_entry.text_field :worked_hours, class: 'form-control', placeholder: 'worked hours' %>
      </div>
    </div>
    <hr/>
  <% end %>
<% else %>
  <span class="badge badge-pill badge-success">Workers</span>
  <a href="javascript:;" id="addNewWorker">Add New Worker</a>
  <div id='worker-fields'>
    <div id='worker-field'>
      <%= render "worker_form_fields", f: f %>
    </div>
  </div>
<% end %>

app/views/bills/_worker_form_fields.html.erb
<div class='row bg-light'>
  <div class='form-group col-md-6'>
    <%= select_tag "workers[]", options_from_collection_for_select(Worker.all, "id", "name"), class: 'form-control' %>
  </div>

  <div class='form-group col-md-6'>
    <%= text_field_tag 'worked_hours[]', nil, class: 'form-control', placeholder: 'worked hours' %>
  </div>
</div>
<hr/>

app/views/bills/edit.html.erb
<% provide(:title, "Create Bill") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0"> Edit bill</h3>
      </div>
      <div class="card-body">
          <% if @bill.errors.any? %>
            <div class= "alert alert-danger">
              <%= @bill.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for @bill do |f| %>
            
            <%= render "form_fields", f: f %>

            <%= f.submit "Update", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", bills_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>

app/views/bills/index.html.erb
<div class="jumbotron bg-light jumbotron-fluid text-center">
  <h3>Bills</h3>
</div>
<div class="Rtable Rtable--4cols Rtable--collapse js-RtableAccordions">
  <% @bills.each_with_index do |bill, i| %>
    <%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-outline-success btn-sm' %>
    <%= link_to 'Delete', bill_path(bill), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: 'btn btn-outline-danger btn-sm' %>

    <button class="Accordion" role="tab" aria-selected="false"><%= bill.number + " - "+bill.title %></button>
    
    <div class="Rtable-cell  Rtable-cell--head"><h3>Project Name : <%= bill.project.name %></h3></div>
    <div class="Rtable-cell"><h3>Client Name : <%= bill.client.name %></h3></div>
    <div class="Rtable-cell"><h3>Labour Charge : <%= bill.labour_charge %></h3></div>
    <div class="Rtable-cell"><h3>Material Charge : <%= bill.material_charge %></h3></div>
    <div class="Rtable-cell"><h3>Total Payable : <%= bill.total_payable %></h3></div>
    <div class="Rtable-cell"><h3>Paid Amount: <%= bill.paid_amount %></h3></div>
    <div class="Rtable-cell"><h3>Balance Amount: <%= bill.balance_amount %></h3></div>
    <div class="Rtable-cell"><h3>Issued On: <%= bill.issued_at %></h3></div>

    <div class="Rtable-cell">
      <% if bill.worker_entries.any? %>
        <span class="badge badge-pill badge-success">Workers</span>
        <% bill.worker_entries.each_with_index do |entry, i| %>
          <h3> <%= entry.worker.name %> - <%= entry.worked_hours || 0 %> hrs</h3>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bills/new.html.erb
<% provide(:title, "Create Bill") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new bill</h3>
      </div>
      <div class="card-body">
          <% if @bill.errors.any? %>
            <div class= "alert alert-danger">
              <%= @bill.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for(:bill, url: bills_path) do |f| %>
            
            <%= render "form_fields", f: f %>

            <%= f.submit "Save", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", root_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>