config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#dashboard'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  # get '/dashboard', to: 'sessions#dashboard'

  devise_scope :user do
    root 'sessions#dashboard', as: :authenticated_root
    resources :workers
    # resources :projects
    resources :clients do
      get 'bills', to: 'clients#bills'
    end
    resources :bills
    resources :projects do
      get 'bills', to: 'projects#bills'
    end
  end

  root 'devise/sessions#new'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :bills
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  def paid_bills
    bills.paid_bills
  end

  def pending_bills
    bills.pending_bills
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :find_project, only: %i[show edit update destroy bills]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: 'The project was created!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @project.update_attributes(project_params)
    redirect_to projects_path, notice: 'Updated successfully'
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Deleted successfully'
  end

  def bills
    @bills = @project.bills
    @pending_bills = @project.pending_bills
    @paid_bills = @project.paid_bills
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project
    project_id = params[:id] || params[:project_id]
    @project = Project.find_by_id(project_id)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_form_fields.html.erb
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <div class="invalid-feedback">name</div>
</div>

app/views/projects/bills.html.erb
<h2><%= @project.name %> Bill Summary</h2>
<p>Summerise your bills here .</p>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#all-bills">All Bills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#pending-bills">Pending Bills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#paid-bills">Paid Bills</a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane container active" id="all-bills">
    <%= render 'bills/bills_info', bills: @bills, layout: '' %>
  </div>

  <div class="tab-pane container fade" id="pending-bills">
    <%= render 'bills/bills_info', bills: @pending_bills, layout: '' %>
  </div>

  <div class="tab-pane container fade" id="paid-bills">
    <%= render 'bills/bills_info', bills: @paid_bills,  layout: '' %>
  </div>
</div>

app/views/projects/edit.html.erb
<% provide(:title, "Create Project") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new project</h3>
      </div>
      <div class="card-body">
          <% if @project.errors.any? %>
            <div class= "alert alert-danger">
              <%= @project.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for @project do |f| %>

            <%= render "form_fields", f: f %>

            <%= f.submit "Update", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", projects_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>

app/views/projects/index.html.erb
<div class="jumbotron bg-light jumbotron-fluid text-center">
  <h3>Projects</h3>
</div>
<div class="Rtable Rtable--4cols Rtable--collapse js-RtableAccordions">
  <% @projects.each_with_index do |project, i| %>
    <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-outline-success btn-sm' %>
    <%= link_to 'Delete', project_path(project), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: 'btn btn-outline-danger btn-sm' %>
    <%= link_to 'View Bills', project_bills_path(project), class: 'btn btn-outline-success btn-sm' %>
    <button class="Accordion" role="tab" aria-selected="false"><%= project.name %></button>
    <div class="Rtable-cell  Rtable-cell--head"><h3>There is no more more info about <%= project.name %> project</h3></div>
  <% end %>
</div>

app/views/projects/new.html.erb
<% provide(:title, "Create Project") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new project</h3>
      </div>
      <div class="card-body">
          <% if @project.errors.any? %>
            <div class= "alert alert-danger">
              <%= @project.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for(:project, url: projects_path) do |f| %>

            <%= render "form_fields", f: f %>

            <%= f.submit "Save", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", root_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>