config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#dashboard'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  # get '/dashboard', to: 'sessions#dashboard'

  devise_scope :user do
    root 'sessions#dashboard', as: :authenticated_root
    resources :workers
    # resources :projects
    resources :clients do
      get 'bills', to: 'clients#bills'
    end
    resources :bills
    resources :projects do
      get 'bills', to: 'projects#bills'
    end
  end

  root 'devise/sessions#new'
end

app/models/worker.rb
# frozen_string_literal: true

class Worker < ApplicationRecord
  has_many :worker_entries, inverse_of: :worker, dependent: :destroy
  has_many :bills, through: :worker_entries
  # has_many :bills, -> { distinct }, through: :worker_entries

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :address, :phone, presence: true
  validates :daily_wage, :overtime_amount, numericality: true
  validates :phone, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  VALID_MOBILE_REGEX = /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/
  validates :phone, presence: true, length: { maximum: 255 },
                    format: { with: VALID_MOBILE_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/workers_controller.rb
# frozen_string_literal: true

class WorkersController < ApplicationController
  before_action :find_worker, only: %i[show edit update destroy]

  def index
    @workers = Worker.all
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to workers_path, notice: 'The worker was created!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @worker.update_attributes(worker_params)
    redirect_to workers_path, notice: 'Updated successfully'
  end

  def destroy
    @worker.destroy
    redirect_to workers_path, notice: 'Delete success'
  end

  private

  def worker_params
    params.require(:worker).permit(:name, :phone, :address, :daily_wage, :overtime_amount)
  end

  def find_worker
    @worker = Worker.find_by_id(params[:id])
  end
end

app/helpers/workers_helper.rb
# frozen_string_literal: true

module WorkersHelper
end

app/views/workers/_form_fields.html.erb
 <div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <div class="invalid-feedback">name</div>
</div>

<div class='form-group'>
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
  <div class="invalid-feedback">phone</div>
</div>

<div class='form-group'>
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  <div class="invalid-feedback">address</div>
</div>

<div class='form-group'>
  <%= f.label :daily_wage %>
  <%= f.text_field :daily_wage, class: 'form-control' %>
  <div class="invalid-feedback">Daily Wage</div>
</div>

<div class='form-group'>
  <%= f.label :overtime_amount %>
  <%= f.text_field :overtime_amount, class: 'form-control' %>
  <div class="invalid-feedback">Overtime Amount</div>
</div>

app/views/workers/edit.html.erb
<% provide(:title, "Create Worker") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new worker</h3>
      </div>
      <div class="card-body">
          <% if @worker.errors.any? %>
            <div class= "alert alert-danger">
              <%= @worker.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for @worker do |f| %>

            <%= render "form_fields", f: f %>
            
            <%= f.submit "Update", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", workers_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>

app/views/workers/index.html.erb
<div class="jumbotron bg-light jumbotron-fluid text-center">
  <h3>Workers</h3>
</div>
<div class="Rtable Rtable--4cols Rtable--collapse js-RtableAccordions">
  <% @workers.each_with_index do |worker, i| %>
    <%= link_to 'Edit', edit_worker_path(worker), class: 'btn btn-outline-success btn-sm' %>
    <%= link_to 'Delete', worker_path(worker), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: 'btn btn-outline-danger btn-sm' %> 
    
    <button class="Accordion" role="tab" aria-selected="false"><%= worker.name %></button>
    <div class="Rtable-cell  Rtable-cell--head"><h3><%= worker.try(:phone) %></h3></div>
    <p class="Rtable-cell"><%= worker.try(:address) %></p>
    <div class="Rtable-cell">Dialy Wage: <%= worker.try(:daily_wage) %></div>
    <div class="Rtable-cell  Rtable-cell--foot">Overtime Amount: <%= worker.try(:overtime_amount) %></div>
  <% end %>
</div>

app/views/workers/new.html.erb
<% provide(:title, "Create Worker") %>
<div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3">
  <span class="anchor" id="formLogin"></span>
  <!-- form card login with validation feedback -->
  <div class="card card-outline-secondary">

      <div class="card-header">
          <h3 class="mb-0">Create new worker</h3>
      </div>
      <div class="card-body">
          <% if @worker.errors.any? %>
            <div class= "alert alert-danger">
              <%= @worker.errors.full_messages.first %>
            </div>
          <% end %>
          <%= form_for(:worker, url: workers_path) do |f| %>

            <%= render "form_fields", f: f %>
            
            <%= f.submit "Save", class: "btn btn-success btn-lg float-right" %>

            <%= link_to "Cancel", root_path, class: "btn btn-danger btn-lg float-left nav-link" %>

          <% end %>
      </div>
      <!--/card-body-->
  </div>
  <!-- /form card login -->
</div>